      PROGRAM RANDU

!     FIRST VERSION (SIMPLIFIED)
      
!     1. VARIABLES DECLARATION AND FIRST SCREEN
      
      USE DFPORT
      CHARACTER arquivo*20
      INTEGER n,i
	  REAL u0,u1,uu
 
      WRITE(*,*)'*****************************************************'
      WRITE(*,*)'*           RANDOM NUMBER GENERATION                *' 
	  WRITE(*,*)
      WRITE(*,*)'*****************************************************'
      WRITE(*,*)
      WRITE(*,*)'*****************************************************'
      WRITE(*,*)'* RANDU method, apud Gentle (1998, p.13)            *'
      WRITE(*,*)'*                                                   *'
      WRITE(*,*)'* DEPARTAMENTO DE ENGENHARIA HIDRAULICA E AMBIENTAL *'
      WRITE(*,*)'*                                                   *'
      WRITE(*,*)'* UNIVERSIDADE FEDERAL DO CEARA                     *'
      WRITE(*,*)'*                                                   *'
      WRITE(*,*)'* JOSE CARLOS DE ARAUJO                             *'
      WRITE(*,*)'*                                                   *'
      WRITE(*,*)'* MAY 2004                                          *'
      WRITE(*,*)'*                                                   *'
      WRITE(*,*)'*****************************************************'
      WRITE(*,*)
      WRITE(*,*)

      
!     2. READING FILE NAME AND LENGTH OF SERIES
      
      WRITE(*,*)'Name of the output file: '
      READ(*,'(a20)')arquivo
      OPEN(23,file=arquivo)      
	  WRITE(*,*)'Length of the generated series: '
	  READ(*,*) n
      WRITE(23,3)'Random series generated by RANDU method, apud Gentle (1998, p.13)'
      WRITE(23,1) n
      
!     3. GENERATION OF THE RANDOM SERIES
      u1  = 0.5
      DO i=1,n
!     generation of u1 and u2 using RANDU generator (Gentle, 1998, p.13)
!      CALL RANDOM_NUMBER(u0)
!	  u1 = MODULO(65539*u0,2E31)
!      uu = 10**(INT(LOG10(u1))+1)
!      u1 = u1/uu
      CALL RANDOM_NUMBER(u1)
      WRITE(23,2) u1
	  WRITE(*,2) u1
	  ENDDO
	1 FORMAT(i4)
	2 FORMAT(f8.6)
    3 FORMAT(a65)
      END
